#include <stdint.h>
#include "fat32.h"
#include "ata.h"
#include "drivers.h"

#define FAT32_EOC 0x0ffffff8u
#define FAT32_MAX_CLUSTER 0x0ffffff6u
static uint8_t sector[512]; static uint32_t partition_lba, fat_lba, data_lba, sectors_per_cluster, bytes_per_sector, fat_size, root_cluster; static int mounted;
static uint16_t le16(const uint8_t*p){return(uint16_t)p[0]|((uint16_t)p[1]<<8);} static uint32_t le32(const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);} static uint32_t cluster_lba(uint32_t c){return data_lba+(c-2u)*sectors_per_cluster;} static int valid_cluster(uint32_t c){return c>=2u&&c<=FAT32_MAX_CLUSTER;} static uint32_t next_cluster(uint32_t c){uint32_t l=fat_lba+(c*4u)/bytes_per_sector,o=(c*4u)%bytes_per_sector;if(ata_read_sector(l,sector)!=0)return 0;return le32(sector+o)&0x0fffffffu;}
static void short_name(const uint8_t*e,char*n,uint32_t cap){uint32_t i=0,j;while(i+1u<cap&&i<8u&&e[i]!=' '){n[i]=(char)e[i];i++;}if(e[8]!=' '&&i+1u<cap){n[i++]='.';for(j=8;j<11u&&i+1u<cap&&e[j]!=' ';j++)n[i++]=(char)e[j];}if(cap)n[i<cap?i:cap-1u]=0;}
static void make_83(const char*p,uint8_t*out){uint32_t i;for(i=0;i<11u;i++)out[i]=' ';i=0;while(*p&&*p!='/'&&i<8u){char c=*p++;if(c>='a'&&c<='z')c=(char)(c-'a'+'A');if(c!='.')out[i++]=(uint8_t)c;else{i=8u;break;}}if(*p=='.')p++;i=8u;while(*p&&*p!='/'&&i<11u){char c=*p++;if(c>='a'&&c<='z')c=(char)(c-'a'+'A');out[i++]=(uint8_t)c;}}
static int scan_root(const uint8_t*wanted,uint32_t wanted_index,fat32_file_t*found,char*name,uint32_t cap,uint32_t*size){uint32_t cluster=root_cluster,index=0,s,e,i;while(valid_cluster(cluster)){for(s=0;s<sectors_per_cluster;s++){if(ata_read_sector(cluster_lba(cluster)+s,sector)!=0)return-1;for(e=0;e<bytes_per_sector;e+=32u){const uint8_t*d=sector+e;if(d[0]==0)return-1;if(d[0]==0xe5||d[11]==0x0f||(d[11]&0x08))continue;if(d[11]&0x10){if(!wanted&&wanted_index==index){short_name(d,name,cap);if(size)*size=le32(d+28);return 0;}index++;continue;}if(wanted){for(i=0;i<11u&&d[i]==wanted[i];i++){}if(i==11u){found->first_cluster=(le16(d+20)<<16)|le16(d+26);found->size=le32(d+28);found->position=0;found->directory=0;return 0;}}index++;}}cluster=next_cluster(cluster);if(cluster>=FAT32_EOC)break;}return-1;}
int fat32_mount(void*device){uint32_t fats,reserved,p,ptype;(void)device;if(!ata_present())return-1;if(ata_read_sector(0,sector)!=0)return-1;partition_lba=0;ptype=sector[450];if(sector[510]==0x55&&sector[511]==0xaa&&ptype!=0){for(p=0;p<4u;p++){const uint8_t*e=sector+446u+p*16u;if(e[4]==0x0b||e[4]==0x0c){partition_lba=le32(e+8);break;}}}if(ata_read_sector(partition_lba,sector)!=0)return-1;bytes_per_sector=le16(sector+11);sectors_per_cluster=sector[13];reserved=le16(sector+14);fats=sector[16];fat_size=le32(sector+36);root_cluster=le32(sector+44);if(bytes_per_sector!=512u||sectors_per_cluster==0||fats==0||fat_size==0||!valid_cluster(root_cluster))return-1;fat_lba=partition_lba+reserved;data_lba=fat_lba+fats*fat_size;mounted=1;serial_write("fat32: mounted, root cluster ready\n");return 0;}
int fat32_is_mounted(void){return mounted;} int fat32_open(const char*path,fat32_file_t*file){uint8_t wanted[11];if(!mounted||!path||!file)return-1;while(*path=='/')path++;if(!*path)return-1;make_83(path,wanted);return scan_root(wanted,0,file,0,0,0);}
int32_t fat32_read_file(fat32_file_t*f,void*buffer,uint32_t length){uint8_t*out=(uint8_t*)buffer;uint32_t cluster,skip,done=0,s,take,i;if(!mounted||!f||!buffer||f->directory||f->position>=f->size)return 0;if(length>f->size-f->position)length=f->size-f->position;cluster=f->first_cluster;skip=f->position/(sectors_per_cluster*bytes_per_sector);while(skip--&&valid_cluster(cluster))cluster=next_cluster(cluster);while(done<length&&valid_cluster(cluster)){for(s=(f->position/bytes_per_sector)%sectors_per_cluster;s<sectors_per_cluster&&done<length;s++){uint32_t offset=f->position%bytes_per_sector;if(ata_read_sector(cluster_lba(cluster)+s,sector)!=0)return done?(int32_t)done:-1;take=bytes_per_sector-offset;if(take>length-done)take=length-done;for(i=0;i<take;i++)out[done+i]=sector[offset+i];done+=take;f->position+=take;}cluster=next_cluster(cluster);}return(int32_t)done;}
int fat32_readdir(uint32_t index,char*name,uint32_t capacity,uint32_t*size){if(!mounted||!name||capacity==0)return-1;return scan_root(0,index,0,name,capacity,size);}
