#include <stdint.h>
#include "mm.h"
#include "kernel.h"
#include "drivers.h"
#define MAX_SPACES 32
static uint32_t kernel_directory[1024] __attribute__((aligned(4096))); static uint32_t first_table[1024] __attribute__((aligned(4096))); static uint32_t heap_table[1024] __attribute__((aligned(4096))); static uint32_t *kernel_tables[1024]; static address_space_t spaces[MAX_SPACES]; static uint8_t space_used[MAX_SPACES]; static address_space_t *current_space; static uint8_t copy_page[PAGE_SIZE] __attribute__((aligned(16)));
static void copy_mem(void*d,const void*s,uint32_t n){uint8_t*a=d;const uint8_t*b=s;while(n--)*a++=*b++;} static inline void load_cr3(uint32_t v){__asm__ volatile("mov %0,%%cr3"::"r"(v):"memory");} static inline uint32_t read_cr0(void){uint32_t v;__asm__ volatile("mov %%cr0,%0":"=r"(v));return v;} static inline void write_cr0(uint32_t v){__asm__ volatile("mov %0,%%cr0"::"r"(v):"memory");} static inline void invlpg(uint32_t a){__asm__ volatile("invlpg (%0)"::"r"(a):"memory");}
void vmm_map(uint32_t virt,uint32_t phys,uint32_t flags){uint32_t di=virt>>22,ti=(virt>>12)&1023u;if(!kernel_tables[di])return;kernel_tables[di][ti]=(phys&~0xfffu)|(flags|PAGE_PRESENT);invlpg(virt);} void vmm_unmap(uint32_t virt){uint32_t di=virt>>22,ti=(virt>>12)&1023u;if(kernel_tables[di]){kernel_tables[di][ti]=0;invlpg(virt);}} uint32_t vmm_get_physical(uint32_t virt){uint32_t di=virt>>22,ti=(virt>>12)&1023u;uint32_t*t=kernel_tables[di];if(!t||(t[ti]&PAGE_PRESENT)==0)return 0;return(t[ti]&~0xfffu)|(virt&0xfffu);}
void vmm_init(void){for(uint32_t i=0;i<1024;i++){kernel_directory[i]=0;first_table[i]=i*PAGE_SIZE|PAGE_PRESENT|PAGE_WRITE;heap_table[i]=0;kernel_tables[i]=0;}kernel_directory[0]=(uint32_t)first_table|PAGE_PRESENT|PAGE_WRITE;kernel_directory[0xd0000000u>>22]=(uint32_t)heap_table|PAGE_PRESENT|PAGE_WRITE;kernel_tables[0]=first_table;kernel_tables[0xd0000000u>>22]=heap_table;current_space=0;load_cr3((uint32_t)kernel_directory);write_cr0(read_cr0()|0x80000000u);serial_write("vmm: initialized successfully\n");}
address_space_t*vmm_create_address_space(void){for(uint32_t i=0;i<MAX_SPACES;i++)if(!space_used[i]){address_space_t*s=&spaces[i];space_used[i]=1;for(uint32_t j=0;j<1024;j++)s->page_directory[j]=kernel_directory[j];for(uint32_t t=0;t<8;t++){s->table_used[t]=0;for(uint32_t j=0;j<1024;j++)s->user_tables[t][j]=0;}return s;}return 0;}
void vmm_destroy_address_space(address_space_t*s){if(!s)return;for(uint32_t i=0;i<MAX_SPACES;i++)if(s==&spaces[i]&&space_used[i]){if(current_space==s){current_space=0;load_cr3((uint32_t)kernel_directory);}for(uint32_t t=0;t<8;t++)if(s->table_used[t])for(uint32_t j=0;j<1024;j++)if(s->user_tables[t][j]&PAGE_PRESENT)pmm_free_page(s->user_tables[t][j]&~0xfffu);space_used[i]=0;return;}}
void vmm_switch_address_space(address_space_t*s){if(!s){current_space=0;load_cr3((uint32_t)kernel_directory);return;}current_space=s;load_cr3((uint32_t)s->page_directory);}
address_space_t*vmm_current_address_space(void){return current_space;}
address_space_t*vmm_clone_address_space(address_space_t*source){if(!source)return 0;address_space_t*dest=vmm_create_address_space();if(!dest)return 0;address_space_t*old=current_space;for(uint32_t t=0;t<8;t++)if(source->table_used[t])for(uint32_t j=0;j<1024;j++){uint32_t pte=source->user_tables[t][j];if(!(pte&PAGE_PRESENT))continue;uint32_t va=(t+1u)*0x400000u+j*PAGE_SIZE;uint32_t page=pmm_alloc_page();if(!page){vmm_destroy_address_space(dest);if(old)vmm_switch_address_space(old);return 0;}if(vmm_map_user(dest,va,page,pte&0xfffu)!=0){pmm_free_page(page);vmm_destroy_address_space(dest);if(old)vmm_switch_address_space(old);return 0;}vmm_switch_address_space(source);copy_mem(copy_page,(const void*)va,PAGE_SIZE);vmm_switch_address_space(dest);copy_mem((void*)va,copy_page,PAGE_SIZE);}if(old)vmm_switch_address_space(old);else vmm_switch_address_space(0);return dest;}

int vmm_map_user(address_space_t*s,uint32_t virt,uint32_t phys,uint32_t flags){if(!s||virt<0x400000u||virt>=0xc0000000u)return -1;uint32_t di=virt>>22,ti=(virt>>12)&1023u;if(di<1||di>8)return -1;uint32_t slot=di-1;if(!s->table_used[slot]){s->table_used[slot]=1;s->page_directory[di]=(uint32_t)s->user_tables[slot]|PAGE_PRESENT|PAGE_WRITE|PAGE_USER;}s->user_tables[slot][ti]=(phys&~0xfffu)|(flags|PAGE_PRESENT|PAGE_USER);if(current_space==s)invlpg(virt);return 0;} int vmm_unmap_user(address_space_t*s,uint32_t virt){uint32_t di=virt>>22,ti=(virt>>12)&1023u;if(!s||virt<0x400000u||virt>=0xc0000000u||di<1||di>8||!s->table_used[di-1])return-1;uint32_t*pte=&s->user_tables[di-1][ti];if(!(*pte&PAGE_PRESENT))return-1;pmm_free_page(*pte&~0xfffu);*pte=0;if(current_space==s)invlpg(virt);return 0;} address_space_t*vmm_clone_address_space_cow(address_space_t*source){address_space_t*dest;address_space_t*old;uint32_t t,j,va,pte,flags;if(!source)return 0;dest=vmm_create_address_space();if(!dest)return 0;old=current_space;for(t=0;t<8;t++)if(source->table_used[t])for(j=0;j<1024;j++){pte=source->user_tables[t][j];if(!(pte&PAGE_PRESENT))continue;va=(t+1u)*0x400000u+j*PAGE_SIZE;flags=(pte&0xfffu)|PAGE_COW;flags&=~PAGE_WRITE;source->user_tables[t][j]=(pte&~0xfffu)|flags;if(current_space==source)invlpg(va);if(vmm_map_user(dest,va,pte&~0xfffu,flags)!=0){vmm_destroy_address_space(dest);if(old)vmm_switch_address_space(old);return 0;}pmm_retain_page(pte&~0xfffu);}if(old)vmm_switch_address_space(old);else vmm_switch_address_space(0);return dest;}
uint32_t vmm_user_alloc(address_space_t*s,uint32_t virt,uint32_t pages,uint32_t flags){for(uint32_t i=0;i<pages;i++){uint32_t p=pmm_alloc_page();if(!p)return 0;if(vmm_map_user(s,virt+i*PAGE_SIZE,p,flags)!=0){pmm_free_page(p);return 0;}}return virt;} uint32_t vmm_get_user_physical(address_space_t*s,uint32_t virt){if(!s||virt<0x400000u||virt>=0xc0000000u)return 0;uint32_t di=virt>>22,ti=(virt>>12)&1023u;if(di<1||di>8)return 0;uint32_t slot=di-1; if(!s->table_used[slot])return 0;uint32_t pte=s->user_tables[slot][ti];if(!(pte&PAGE_PRESENT)||(pte&PAGE_USER)==0)return 0;return(pte&~0xfffu)|(virt&0xfffu);} int vmm_validate_user_ptr(address_space_t*s,uint32_t virt,uint32_t len,uint32_t write){if(!s||len==0||virt<0x400000u||virt>=0xc0000000u||len>0xc0000000u-virt)return -1;uint32_t end=virt+len-1u;for(uint32_t page=virt&~(PAGE_SIZE-1u);;page+=PAGE_SIZE){uint32_t phys=vmm_get_user_physical(s,page);if(!phys)return -1;uint32_t di=page>>22,ti=(page>>12)&1023u,slot=di-1u;uint32_t pte=s->user_tables[slot][ti];if(write&&!(pte&PAGE_WRITE)){if(!(pte&PAGE_COW))return-1;vmm_page_fault(6,page);pte=s->user_tables[slot][ti];if(!(pte&PAGE_WRITE))return-1;}if(page>end-PAGE_SIZE)return 0;}}
int vmm_clone_selftest(void){address_space_t*a=vmm_create_address_space();if(!a)return -1;uint32_t p=pmm_alloc_page();if(!p){vmm_destroy_address_space(a);return -1;}if(vmm_map_user(a,0x00401000u,p,PAGE_WRITE)!=0){pmm_free_page(p);vmm_destroy_address_space(a);return -1;}vmm_switch_address_space(a);*(volatile uint8_t*)0x00401000u=0x5au;address_space_t*b=vmm_clone_address_space(a);if(!b){vmm_destroy_address_space(a);return -1;}vmm_switch_address_space(b);int ok=(*(volatile uint8_t*)0x00401000u==0x5au);*(volatile uint8_t*)0x00401000u=0xa5u;vmm_switch_address_space(a);ok=ok&&(*(volatile uint8_t*)0x00401000u==0x5au);vmm_destroy_address_space(b);vmm_destroy_address_space(a);return ok?0:-1;}
int vmm_cow_selftest(void){address_space_t*a=vmm_create_address_space(),*b;uint32_t p;int ok=0;if(!a)return-1;p=pmm_alloc_page();if(!p||vmm_map_user(a,0x00402000u,p,PAGE_WRITE)!=0){if(p)pmm_free_page(p);vmm_destroy_address_space(a);return-1;}vmm_switch_address_space(a);*(volatile uint8_t*)0x00402000u=0x11u;b=vmm_clone_address_space_cow(a);if(b){vmm_switch_address_space(b);vmm_page_fault(6,0x00402000u);*(volatile uint8_t*)0x00402000u=0x22u;vmm_switch_address_space(a);ok=(*(volatile uint8_t*)0x00402000u==0x11u);vmm_destroy_address_space(b);}vmm_destroy_address_space(a);vmm_switch_address_space(0);return ok?0:-1;} void vmm_page_fault(uint32_t error,uint32_t address){uint32_t cr2,page,di,ti,slot,pte,new_page;address_space_t*s;__asm__ volatile("mov %%cr2,%0":"=r"(cr2));s=current_space;page=(address?address:cr2)&~(PAGE_SIZE-1u);di=page>>22;ti=(page>>12)&1023u;slot=di-1u;if(s&&error&2&&error&4&&di>=1&&di<=8&&s->table_used[slot]){pte=s->user_tables[slot][ti];if((pte&PAGE_COW)&& (pte&PAGE_PRESENT)){new_page=pmm_alloc_page();if(!new_page)panic("out of memory resolving COW fault");vmm_map(0x003ff000u,pte&~0xfffu,0);copy_mem(copy_page,(const void*)0x003ff000u,PAGE_SIZE);vmm_map(0x003ff000u,new_page,PAGE_WRITE);copy_mem((void*)0x003ff000u,copy_page,PAGE_SIZE);vmm_map(0x003ff000u,0x003ff000u,PAGE_WRITE);s->user_tables[slot][ti]=(new_page|PAGE_PRESENT|PAGE_USER|PAGE_WRITE);invlpg(page);pmm_free_page(pte&~0xfffu);return;}}kprintf("page fault: addr=0x%x error=0x%x\n",cr2,error);if(!(error&1))kprintf("  reason: not present\n");if(error&2)kprintf("  reason: write\n");if(error&4)kprintf("  reason: user mode\n");panic("unhandled page fault");}
