#include <stdint.h>
#include "acpi.h"
#include "drivers.h"
#include "kernel.h"

typedef struct rsdp_v1 { char signature[8]; uint8_t checksum; char oemid[6]; uint8_t revision; uint32_t rsdt; } __attribute__((packed)) rsdp_v1_t;
typedef struct sdt_header { char signature[4]; uint32_t length; uint8_t revision; uint8_t checksum; char oemid[6]; char oem_table_id[8]; uint32_t oem_revision; uint32_t creator_id; uint32_t creator_revision; } __attribute__((packed)) sdt_header_t;
typedef struct irq_override { uint8_t source; uint32_t gsi; uint16_t flags; } irq_override_t;
static uint32_t lapic_base=0xfee00000u,ioapic_base=0xfec00000u,ioapic_gsi_base,cpu_count=1,override_count;static uint8_t cpu_apic_ids[ACPI_MAX_CPUS];static irq_override_t overrides[ACPI_MAX_IRQ_OVERRIDES];static int madt_found;
static int signature(const uint8_t*p){static const char s[8]={'R','S','D',' ','P','T','R',' '};for(uint32_t i=0;i<8;i++)if(p[i]!=(uint8_t)s[i])return 0;return 1;}
static int valid_rsdp(const uint8_t*p){uint8_t sum=0;for(uint32_t i=0;i<20u;i++)sum=(uint8_t)(sum+p[i]);return sum==0;}
static rsdp_v1_t*scan(uint32_t begin,uint32_t end){for(uint32_t p=begin;p+20u<=end;p+=16u){uint8_t*q=(uint8_t*)p;if(signature(q)&&valid_rsdp(q))return(rsdp_v1_t*)q;}return 0;}
static int valid_sdt(const sdt_header_t*h){uint8_t sum=0;if(!h||h->length<sizeof(sdt_header_t)||h->length>0x10000u)return 0;for(uint32_t i=0;i<h->length;i++)sum=(uint8_t)(sum+((const uint8_t*)h)[i]);return sum==0;}
static int has_sig(const char*a,const char*b){for(uint32_t i=0;i<4u;i++)if(a[i]!=b[i])return 0;return 1;}
static void parse_madt(const sdt_header_t*h){const uint8_t*p=(const uint8_t*)h;uint32_t pos=sizeof(sdt_header_t)+8u;if(h->length<pos)return;madt_found=1;lapic_base=*(const uint32_t*)(p+36u);cpu_count=0;override_count=0;ioapic_gsi_base=0;for(;pos+2u<=h->length;){uint8_t type=p[pos],len=p[pos+1];if(len<2u||pos+len>h->length)break;if(type==0u&&len>=8u){uint32_t flags=*(const uint32_t*)(p+pos+4u);if(flags&1u&&cpu_count<ACPI_MAX_CPUS)cpu_apic_ids[cpu_count++]=p[pos+3u];}else if(type==1u&&len>=12u&&ioapic_base==0xfec00000u){ioapic_base=*(const uint32_t*)(p+pos+4u);ioapic_gsi_base=*(const uint32_t*)(p+pos+8u);}else if(type==2u&&len>=10u&&override_count<ACPI_MAX_IRQ_OVERRIDES){overrides[override_count].source=p[pos+3u];overrides[override_count].gsi=*(const uint32_t*)(p+pos+4u);overrides[override_count].flags=*(const uint16_t*)(p+pos+8u);override_count++;}pos+=len;}if(cpu_count==0)cpu_count=1;}
void acpi_init(void){rsdp_v1_t*r=0;uint16_t ebda=(uint16_t)(*(volatile uint16_t*)0x40e);madt_found=0;lapic_base=0xfee00000u;ioapic_base=0xfec00000u;ioapic_gsi_base=0;cpu_count=1;override_count=0;if(ebda)r=scan((uint32_t)ebda*16u,(uint32_t)ebda*16u+1024u);if(!r)r=scan(0x000e0000u,0x00100000u);if(!r){serial_write("acpi: RSDP not found; legacy platform mode\n");return;}kprintf("acpi: RSDP found revision %u rsdt=0x%x\n",r->revision,r->rsdt);sdt_header_t*rsdt=(sdt_header_t*)(uintptr_t)r->rsdt;if(!valid_sdt(rsdt)||!has_sig(rsdt->signature,"RSDT")){serial_write("acpi: invalid RSDT; legacy platform mode\n");return;}uint32_t entries=(rsdt->length-sizeof(sdt_header_t))/4u;if(entries>64u)entries=64u;for(uint32_t i=0;i<entries;i++){sdt_header_t*h=(sdt_header_t*)(uintptr_t)((*(const uint32_t*)((const uint8_t*)rsdt+sizeof(sdt_header_t)+i*4u)));if(valid_sdt(h)&&has_sig(h->signature,"APIC")){parse_madt(h);break;}}if(madt_found)kprintf("acpi: MADT LAPIC=0x%x IOAPIC=0x%x GSI=%u CPUs=%u overrides=%u\n",lapic_base,ioapic_base,ioapic_gsi_base,cpu_count,override_count);else serial_write("acpi: MADT not found; default APIC topology retained\n");}
int acpi_madt_present(void){return madt_found;}uint32_t acpi_lapic_base(void){return lapic_base;}uint32_t acpi_ioapic_base(void){return ioapic_base;}uint32_t acpi_ioapic_gsi_base(void){return ioapic_gsi_base;}uint32_t acpi_cpu_count(void){return cpu_count;}uint8_t acpi_cpu_apic_id(uint32_t index){return index<cpu_count?cpu_apic_ids[index]:0;}int acpi_irq_to_gsi(uint8_t irq,uint32_t*gsi,uint16_t*flags){if(!gsi||!flags)return-1;*gsi=irq;*flags=0;for(uint32_t i=0;i<override_count;i++)if(overrides[i].source==irq){*gsi=overrides[i].gsi;*flags=overrides[i].flags;return 1;}return 0;}
